name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn package
      run: |
        set -e
        ./mvnw -V package
    - name: upload package
      uses: actions/upload-artifact@v2.3.1
      with: 
        name: acmeair-jar
        path: target/acmeair-*.jar
